### ISSUE TITLE
:bug: grammar doesn't support color types

### ISSUE THREAD

**Issue by rneswold** [DrMemCS/drmem#101]
When I added the color type to the API, I forgot to add support to the grammar used by logic blocks.

The format should be `#rrggbb` where `rr`, `gg`, and `bb` are two hex digits. Also, since we're using the `palette` crate for our color calculations, see if it recognizes common color names. If so, we could also support `#color` as value.

**Comment by beauremus** [comment]
I'm interested in working on this issue ✋🏻

**Comment by rneswold** [comment]
Argh. Sorry. I wanted to start a RGB LED bulb driver so I needed this sooner than later, so I just did it without visiting GitHub first.
